### ISSUE TITLE
Errors using example create_env

### ISSUE THREAD

**Issue by dmnk1308** [ZhengyiLuo/SMPLSim#1]
Hi Zhengyi, 
First of all, thank you for making your work publicly available!
Using your example in `create_env.py`, I am trying to set up an environment in which the motions from the AMASS dataset are available as trajectories. This will cause some problems
1) In the example you use an AMASS file that I cannot find and seems to be for Isaac and not for Mujoco. Can I simply download the SMPLH version of AMASS and concatenate individual trajectories? 
2) The range of the action space is not between -1 and 1 for the SMPL model when creating the environment and I get an error.
3) Some functions like `get_body_qposaddr` or `get_body_qveladdr` have no reference to the function definition in `smplenv.py`. I assume the reference to `mujoco_utils.py` is missing here?

Thank you very much for your help

**Comment by ZhengyiLuo** [comment]
Sorry for the late reply! 

Please use `python examples/env_humanoid_test.py  headless=False` to test out the environment. 

As for the range of actions, it should be between -1 and 1. Could you point me to what is the error? 

`get_body_qposaddr` is in [here](https://github.com/ZhengyiLuo/SMPLSim/blob/3984c9023b8ac8aa4f80731e232a2220d72c059b/smpl_sim/utils/mujoco_utils.py#L5)

**Comment by Rowing0914** [comment]
@dmnk1308 FYI, I found the likely motion files for this example.
- https://github.com/ZhengyiLuo/PULSE/blob/master/download_data.sh#L3
