### ISSUE TITLE
Running motion_test.py, but cannot find file: "motions = joblib.load("/hdd/zen/data/ActBound/AMASS/amass_copycat_take6_test.pkl")"

### ISSUE THREAD

**Issue by chenyunzhanggit** [ZhengyiLuo/SMPLSim#8]
as title. can not find amass_copycat_take6_test.pkl

**Comment by ZhengyiLuo** [comment]
That is a motion file that needs to be processed from AMASS. Please follow the instruction from [PHC](https://github.com/ZhengyiLuo/PHC).
